/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package gui.internalFrames;

import java.io.File;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logic.BLAudioPlayer;
import logic.BLMusic;
import logic.BLPlaylist;
import logic.BLSong;
import structures.node.Nodo;
import structures.object.Playlist;
import structures.object.Song;

/**
 *
 * @author marck
 */
public class InfRegisterSong extends javax.swing.JInternalFrame {
    BLMusic b = new BLMusic();
    DefaultTableModel modelo = new DefaultTableModel();
    /**
     * Creates new form InfRegisterSong
     */
    public InfRegisterSong() {
        initComponents();
        inicializarTabla();
        llenarCbx() ;
    }
    
    private void inicializarTabla() {
        String[] titulos = {"Nombre", "Artista", "Género", "Duración", "Playlist"};
        modelo.setColumnIdentifiers(titulos);
        tblPlaylist.setModel(modelo);
    }
    
    public void mostrar(DefaultTableModel modelo) {
        Nodo<Song> inicio = b.CircularListSongs(); 
        Nodo<Song> actual = inicio.getSgte(); 
        int cont = 0;
        do {
            cont++;
            actual = actual.getSgte();
        } while (actual != inicio.getSgte());
        Object[][] datos = new Object[cont][5];
        String[] titulos = {"Nombre", "Artista", "Género", "Duración", "Playlist"};
        actual = inicio.getSgte();
        int i = 0;
        do {
            datos[i][0] = actual.getInfo().getSongName();
            datos[i][1] = actual.getInfo().getArtistName();
            datos[i][2] = actual.getInfo().getGenre();
            datos[i][3] = actual.getInfo().getDuration();
            datos[i][4] = actual.getInfo().getNamePlaylist();
            i++;
            actual = actual.getSgte();
        } while (actual != inicio.getSgte());
        modelo.setDataVector(datos, titulos);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        lblCancionNom = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblArtist = new javax.swing.JLabel();
        txtArtist = new javax.swing.JTextField();
        lblGenre = new javax.swing.JLabel();
        cbxGenre = new javax.swing.JComboBox<>();
        lblPath = new javax.swing.JLabel();
        txtPath = new javax.swing.JTextField();
        btnFileChooser = new javax.swing.JButton();
        lblPlaylist = new javax.swing.JLabel();
        cbxPlaylist = new javax.swing.JComboBox<>();
        btnAddToPlaylist = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPlaylist = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        ctrlClose = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();

        background.setBackground(new java.awt.Color(255, 255, 255));

        lblCancionNom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCancionNom.setText("Nombre Canción");

        lblArtist.setText("Nombre Artista");

        txtArtist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArtistActionPerformed(evt);
            }
        });

        lblGenre.setText("Genero Musical");

        cbxGenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pop", "Salsa", "Electronica", "Tongo", "Rock", "Villancicos" }));


        lblPath.setText("Direccion Archivo");

        txtPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPathActionPerformed(evt);
            }
        });

        btnFileChooser.setText("Cargar Archivo");
        btnFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileChooserActionPerformed(evt);
            }
        });

        lblPlaylist.setText("Playlist");

        cbxPlaylist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Playlist" }));

        btnAddToPlaylist.setText("Agregar");
        btnAddToPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToPlaylistActionPerformed(evt);
            }
        });

        tblPlaylist.setModel(modelo);
        jScrollPane1.setViewportView(tblPlaylist);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        ctrlClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/icons/close.png"))); // NOI18N
        ctrlClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ctrlCloseMouseClicked(evt);
            }
        });

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Registrar Canción");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ctrlClose)
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ctrlClose)
                    .addComponent(lblTitle))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addComponent(lblPlaylist)
                                .addGap(226, 226, 226)
                                .addComponent(cbxPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCancionNom)
                                    .addComponent(lblArtist)
                                    .addComponent(lblGenre))
                                .addGap(55, 55, 55)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxGenre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(113, 113, 113))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(lblPath)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)))
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFileChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(btnAddToPlaylist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnFileChooser)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addComponent(lblCancionNom)
                                .addGap(44, 44, 44)
                                .addComponent(lblArtist))
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGenre)
                            .addComponent(cbxGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPath)
                            .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblPlaylist))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddToPlaylist))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtArtistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArtistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtArtistActionPerformed

    private void txtPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPathActionPerformed

    private void btnFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFileChooserActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            txtPath.setText(selectedFile.getAbsolutePath());
        }
    }//GEN-LAST:event_btnFileChooserActionPerformed

    private void btnAddToPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToPlaylistActionPerformed
        String name, genre, playlist, artist,path;
        double duration;
        int res;
        name = txtName.getText();
        artist = txtArtist.getText();
        genre = cbxGenre.getSelectedItem().toString();
        playlist = String.valueOf(cbxPlaylist.getSelectedItem());
        System.out.println(playlist);
        path = txtPath.getText();
        duration = BLAudioPlayer.getDuration(path);

        res =BLSong.insertar(name, artist, path, genre, duration, playlist);
        if (res == 0) { 
            Song temp = new Song(name, artist, path, genre, duration, playlist);
            b.addSong(temp); 
            mostrar(modelo);
            JOptionPane.showMessageDialog(null, "Canción registrada exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if(res==1 || res==3){
                JOptionPane.showMessageDialog(null, "No se pudo registrar la canción", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
        txtName.setText("");
        txtArtist.setText("");
        txtPath.setText("");
        cbxGenre.setSelectedIndex(0);
        cbxPlaylist.setSelectedIndex(0);
        txtName.requestFocus();
    }//GEN-LAST:event_btnAddToPlaylistActionPerformed

    private void ctrlCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ctrlCloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_ctrlCloseMouseClicked

    private void llenarCbx() {
        list = BLPlaylist.list();
        iterator = list.iterator();
        while(iterator.hasNext()) {
            obj = iterator.next();
            cbxPlaylist.addItem(obj.getName());
        }     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnAddToPlaylist;
    private javax.swing.JButton btnFileChooser;
    private javax.swing.JComboBox<String> cbxGenre;
    private javax.swing.JComboBox<String> cbxPlaylist;
    private javax.swing.JLabel ctrlClose;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblArtist;
    private javax.swing.JLabel lblCancionNom;
    private javax.swing.JLabel lblGenre;
    private javax.swing.JLabel lblPath;
    private javax.swing.JLabel lblPlaylist;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblPlaylist;
    private javax.swing.JTextField txtArtist;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPath;
    // End of variables declaration//GEN-END:variables
    private Iterator<Playlist> iterator;
    private Playlist obj;
    private ArrayList<Playlist> list;
}
